/**
 * Generated by src/pjamm/generate-zones.ts from Natural Earth 1:50m admin-0
 * countries (public domain), pinned to tag v5.1.2. Do not edit by hand.
 * Regenerate with: bun src/pjamm/generate-zones.ts
 */

import type { BoundingBox } from "./types";

export const GENERATED_COUNTRY_ZONES: {
  id: number;
  name: string;
  boxes: BoundingBox[];
}[] = [
  {
    id: 1,
    name: "United States",
    boxes: [
      { south: 50.6, west: -179.19, north: 72.41, east: -129.01 },
      { south: 50.37, west: 176.25, north: 53.11, east: 180 },
      { south: 51.36, west: 171.49, north: 54.01, east: 174.78 },
      { south: 17.96, west: -161.24, north: 23.22, east: -153.8 },
      { south: 23.54, west: -125.71, north: 50.37, east: -65.99 },
    ],
  },
  {
    id: 37,
    name: "Italy",
    boxes: [{ south: 35.69, west: 5.63, north: 48.08, east: 19.49 }],
  },
  {
    id: 61,
    name: "France",
    boxes: [
      { south: 40.38, west: -5.76, north: 52.1, east: 10.56 },
      { south: -13.98, west: 44.04, north: -11.65, east: 46.22 },
      { south: -22.37, west: 54.23, north: -19.87, east: 56.84 },
      { south: 13.43, west: -62.79, north: 17.51, east: -59.83 },
      { south: 1.12, west: -55.62, north: 6.78, east: -50.65 },
    ],
  },
  {
    id: 62,
    name: "United Kingdom",
    boxes: [{ south: 49.02, west: -9.14, north: 61.83, east: 2.75 }],
  },
  {
    id: 64,
    name: "Switzerland",
    boxes: [{ south: 44.83, west: 4.97, north: 48.78, east: 11.45 }],
  },
  {
    id: 65,
    name: "Austria",
    boxes: [{ south: 45.4, west: 8.52, north: 50, east: 18.15 }],
  },
  {
    id: 66,
    name: "Spain",
    boxes: [
      { south: 35.03, west: -10.24, north: 44.76, east: 5.32 },
      { south: 26.65, west: -19.16, north: 30.24, east: -12.42 },
    ],
  },
  {
    id: 79,
    name: "Germany",
    boxes: [{ south: 46.28, west: 4.86, north: 56.06, east: 16.02 }],
  },
  {
    id: 140,
    name: "Canada",
    boxes: [{ south: 40.67, west: -142, north: 84.12, east: -51.65 }],
  },
  {
    id: 146,
    name: "Croatia",
    boxes: [{ south: 41.43, west: 12.52, north: 47.53, east: 20.4 }],
  },
  {
    id: 193,
    name: "Norway",
    boxes: [
      { south: 57.02, west: 3.8, north: 72.14, east: 31.96 },
      { south: 69.83, west: -10.1, north: 72.18, east: -6.98 },
      { south: 73.35, west: 17.8, north: 75.52, east: 20.27 },
      { south: 75.58, west: 9.56, north: 81.48, east: 34.63 },
    ],
  },
  {
    id: 196,
    name: "Chile",
    boxes: [
      { south: -28.17, west: -110.43, north: -26.07, east: -108.22 },
      { south: -34.67, west: -79.99, north: -32.58, east: -77.77 },
      { south: -56.89, west: -76.71, north: -16.51, east: -65.44 },
    ],
  },
  {
    id: 200,
    name: "Portugal",
    boxes: [
      { south: 31.65, west: -18.24, north: 33.87, east: -15.69 },
      { south: 36.01, west: -10.48, north: 43.14, east: -5.21 },
      { south: 35.94, west: -29.84, north: 39.8, east: -24.03 },
      { south: 38.36, west: -32.28, north: 40.52, east: -30.14 },
    ],
  },
  {
    id: 202,
    name: "Taiwan",
    boxes: [{ south: 20.93, west: 117.29, north: 26.28, east: 122.93 }],
  },
  {
    id: 203,
    name: "Japan",
    boxes: [
      { south: 25.09, west: 126.65, north: 46.51, east: 146.83 },
      { south: 23.27, west: 122.68, north: 25.87, east: 126.44 },
    ],
  },
  {
    id: 204,
    name: "Colombia",
    boxes: [{ south: -5.24, west: -80.03, north: 13.43, east: -65.88 }],
  },
  {
    id: 205,
    name: "Thailand",
    boxes: [{ south: 4.64, west: 96.37, north: 21.42, east: 106.64 }],
  },
  {
    id: 206,
    name: "Bolivia",
    boxes: [{ south: -23.89, west: -70.65, north: -8.71, east: -56.5 }],
  },
  {
    id: 207,
    name: "Australia",
    boxes: [
      { south: -44.62, west: 111.91, north: -9.05, east: 154.62 },
      { south: -55.75, west: 157.84, north: -53.47, east: 159.96 },
    ],
  },
  {
    id: 212,
    name: "Mexico",
    boxes: [{ south: 13.55, west: -119.4, north: 33.72, east: -85.7 }],
  },
  {
    id: 213,
    name: "Belgium",
    boxes: [{ south: 48.51, west: 1.52, north: 52.49, east: 7.36 }],
  },
  {
    id: 214,
    name: "Ireland",
    boxes: [{ south: 50.47, west: -11.39, north: 56.37, east: -5.03 }],
  },
  {
    id: 292,
    name: "New Zealand",
    boxes: [
      { south: -48.26, west: 165.48, north: -33.43, east: 179.54 },
      { south: -53.57, west: 168.02, north: -51.49, east: 170.23 },
      { south: -51.85, west: 164.89, north: -49.53, east: 167.27 },
      { south: -45.33, west: -177.85, north: -42.72, east: -175.12 },
      { south: -10.36, west: -173.5, north: -7.55, east: -170.19 },
    ],
  },
  {
    id: 302,
    name: "Andorra",
    boxes: [{ south: 41.43, west: 0.41, north: 43.64, east: 2.74 }],
  },
  {
    id: 305,
    name: "China",
    boxes: [{ south: 17.22, west: 72.61, north: 54.56, east: 135.75 }],
  },
  {
    id: 313,
    name: "Slovakia",
    boxes: [{ south: 46.76, west: 15.86, north: 50.6, east: 23.54 }],
  },
  {
    id: 314,
    name: "Romania",
    boxes: [{ south: 42.67, west: 19.24, north: 49.26, east: 30.71 }],
  },
  {
    id: 373,
    name: "Saudi Arabia",
    boxes: [{ south: 15.37, west: 33.62, north: 33.12, east: 56.64 }],
  },
  {
    id: 375,
    name: "Peru",
    boxes: [{ south: -19.35, west: -82.34, north: 0.96, east: -67.69 }],
  },
  {
    id: 404,
    name: "Brazil",
    boxes: [{ south: -34.74, west: -75, north: 6.26, east: -33.81 }],
  },
];
